#!/bin/bash
case "$1" in
    start-server) exit 0 ;;
    devices) printf 'List of devices attached\n' ;;
    mdns) printf 'adb-test\t_adb-tls-connect._tcp\t192.0.2.15:39111\n' ;;
    connect) [ "$2" = "192.0.2.15:39111" ] ;;
    -s) [ "$2" = "192.0.2.15:39111" ] && [ "$3" = "get-state" ] && printf 'device\n' ;;
    *) exit 1 ;;
esac
