#!/bin/bash
printf '%s\n' "$*" >>"$PHONE_SCREEN_CACHE_DIR/adb-calls"
case "$1" in
    start-server) exit 0 ;;
    devices) printf 'List of devices attached\n192.0.2.10:37123\tdevice product:test model:Test_Phone\n' ;;
    mdns)
        printf 'adb-test\t_adb-tls-connect._tcp\t192.0.2.10:37123\n'
        printf 'adb-test (2)\t_adb-tls-connect._tcp\t192.0.2.10:49999\n'
        ;;
    connect) exit 0 ;;
    -s)
        [ "$3" = "get-state" ] && printf 'device\n'
        [ "$3" = "shell" ] && [ "$5" = "ro.serialno" ] && printf 'PHONE-ONE\n'
        ;;
    *) exit 0 ;;
esac
