#!/bin/bash
case "$1" in
    start-server) exit 0 ;;
    devices) printf 'List of devices attached\n192.0.2.10:49999\tdevice product:test model:Test_Phone\n' ;;
    mdns) printf 'adb-test\t_adb-tls-connect._tcp\t192.0.2.10:49999\n' ;;
    connect) [ "$2" = "192.0.2.10:49999" ] ;;
    -s)
        [ "$2" = "192.0.2.10:49999" ] || exit 1
        [ "$3" = "get-state" ] && printf 'device\n'
        [ "$3" = "shell" ] && [ "$5" = "ro.serialno" ] && printf 'PHONE-ONE\n'
        ;;
    *) exit 1 ;;
esac
